name: Database migrate

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    if: ${{ secrets.DATABASE_URL_UNPOOLED != '' }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm db:migrate
        env:
          DATABASE_URL_UNPOOLED: ${{ secrets.DATABASE_URL_UNPOOLED }}
